#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

#@ start_bosh_b64 = base64.encode(data.values.start_bosh_script)

---
resources:
  - name: bosh-docker-cpi-image
    type: registry-image
    icon: docker
    source:
      repository: bosh/docker-cpi

  - name: warden-cpi-repo
    type: git
    icon: github
    source:
      uri: https://github.com/rkoster/noble-concourse-nested-cpi-validation.git
      branch: main

  - name: bosh-deployment-repo
    type: git
    icon: github
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: master

  - name: warden-cpi-containerd-image
    type: registry-image
    icon: docker
    source:
      repository: ((docker_registry_host))/warden-cpi-containerd
      username: admin
      password: ((docker_registry_password))
      insecure_registries: ["((docker_registry_host))"]

  - name: zookeeper-release
    type: git
    icon: github
    source:
      uri: https://github.com/cppforlife/zookeeper-release
      branch: master

jobs:
  - name: build-warden-cpi-containerd-image
    plan:
      - in_parallel:
          - get: warden-cpi-repo
            trigger: false
          - get: bosh-deployment-repo

      - task: build-image
        privileged: true
        params:
          DOCKER_REGISTRY_HOST: ((docker_registry_host))
          DOCKER_REGISTRY_USERNAME: admin
          DOCKER_REGISTRY_PASSWORD: ((docker_registry_password))
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
              tag: noble
          inputs:
            - name: warden-cpi-repo
            - name: bosh-deployment-repo
          run:
            path: bash
            args:
              - -c
              - |
                set -euxo pipefail
                
                echo "=== Installing Docker ==="
                apt-get update && apt-get install -y docker.io
                
                echo "=== Starting Docker daemon ==="
                mkdir -p /var/lib/docker
                dockerd --data-root /scratch/docker &
                DOCKERD_PID=$!
                
                # Wait for Docker to be ready
                echo "Waiting for Docker daemon to start..."
                for i in {1..30}; do
                  if docker info >/dev/null 2>&1; then
                    echo "Docker daemon is ready"
                    break
                  fi
                  echo "Waiting... ($i/30)"
                  sleep 2
                done
                
                if ! docker info >/dev/null 2>&1; then
                  echo "ERROR: Docker daemon failed to start"
                  exit 1
                fi
                
                echo "=== Building warden-cpi image with containerd support ==="
                
                # Prepare build context
                cd warden-cpi-repo/warden-cpi-containerd
                cp -r ../../bosh-deployment-repo bosh-deployment
                
                # Build image
                docker build \
                  --build-arg BASE_IMAGE=ubuntu:noble \
                  -t ${DOCKER_REGISTRY_HOST}/warden-cpi-containerd:latest \
                  .
                
                # Configure Docker daemon for insecure registry
                echo '{"insecure-registries": ["10.246.0.21:5000"]}' > /etc/docker/daemon.json
                
                # Restart dockerd to apply config
                kill $DOCKERD_PID
                sleep 2
                dockerd --data-root /scratch/docker &
                DOCKERD_PID=$!
                
                # Wait for Docker to be ready again
                for i in {1..15}; do
                  if docker info >/dev/null 2>&1; then
                    echo "Docker daemon restarted with insecure registry config"
                    break
                  fi
                  sleep 2
                done
                
                # Push image without login (registry allows it)
                docker push ${DOCKER_REGISTRY_HOST}/warden-cpi-containerd:latest
                
                echo "=== Image built and pushed successfully ==="
                
                # Cleanup
                kill $DOCKERD_PID || true

  - name: deploy-zookeeper-on-docker-bosh
    plan:
      - in_parallel:
          - get: bosh-docker-cpi-image
          - get: zookeeper-release
            trigger: false

      - task: start-bosh-and-deploy-zookeeper
        image: bosh-docker-cpi-image
        privileged: true
        config:
          platform: linux
          inputs:
            - name: zookeeper-release
          run:
            path: bash
            args:
              - -c
              - #@ "set -euo pipefail\n\necho \"=== Checking Disk Space ===\"\ndf -h /scratch\n\necho \"=== Cleaning up previous builds ===\"\nrm -rf /scratch/docker /tmp/local-bosh /tmp/tmp.* /root/.bosh || true\ndf -h /scratch\n\necho \"=== Creating patched start-bosh script from base64 ===\"\ncp /usr/local/bin/start-bosh /usr/local/bin/start-bosh.original\n\n# Decode base64-encoded patched script\nbase64 -d > /usr/local/bin/start-bosh <<'BASE64SCRIPT'\n" + start_bosh_b64 + "\nBASE64SCRIPT\n\nchmod +x /usr/local/bin/start-bosh\n\necho \"=== Starting BOSH Director with Docker CPI (patched version) ===\"\nstart-bosh\n\n# Source the environment variables\nsource /tmp/local-bosh/director/env\n\necho \"=== BOSH Director Environment ===\"\necho \"BOSH_ENVIRONMENT: ${BOSH_ENVIRONMENT}\"\necho \"BOSH_CLIENT: ${BOSH_CLIENT}\"\n\necho \"=== Verifying BOSH Director ===\"\nbosh env\n\necho \"=== Cloud Config ===\"\nbosh cloud-config\n\necho \"=== Creating and Uploading Zookeeper Release ===\"\ncd zookeeper-release\nbosh create-release --force --timestamp-version\nbosh upload-release\ncd ..\n\necho \"=== Uploading Stemcell ===\"\nbosh upload-stemcell --sha1 86662513fbbb9200aca8f0c24fa69e822f49e18c \\\n  https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-jammy-go_agent?v=1.631\n\necho \"=== Creating ops-file for single instance ===\"\ncat > /tmp/single-instance.yml <<'OPSFILE'\n---\n# Ops-file to deploy a single zookeeper instance instead of 5\n- type: replace\n  path: /instance_groups/name=zookeeper/instances\n  value: 1\n\n- type: replace\n  path: /instance_groups/name=zookeeper/azs\n  value: [z1]\n\n# Remove smoke-tests errand for simplicity\n- type: remove\n  path: /instance_groups/name=smoke-tests\n\n# Update stemcell to jammy\n- type: replace\n  path: /stemcells/alias=default/os\n  value: ubuntu-jammy\nOPSFILE\n\necho \"=== Deploying Zookeeper (Single Instance) ===\"\nbosh -n deploy \\\n  -d zookeeper \\\n  zookeeper-release/manifests/zookeeper.yml \\\n  -o /tmp/single-instance.yml\n\necho \"=== Deployment Status ===\"\nbosh -d zookeeper instances\n\necho \"=== Zookeeper VMs ===\"\nbosh -d zookeeper vms\n\necho \"=== Testing Zookeeper ===\"\n# SSH into the instance and check zookeeper status\nbosh -d zookeeper ssh zookeeper/0 -c \"\n  set -e\n  echo '=== Zookeeper Process Status ==='\n  sudo /var/vcap/bosh/bin/monit summary\n  \n  echo '=== Zookeeper Server Status ==='\n  echo stat | nc localhost 2181 || echo 'Could not connect to Zookeeper'\n\"\n\necho \"=== Cleaning Up ===\"\nbosh -d zookeeper -n delete-deployment\n\necho \"=== Pipeline Complete ===\"\n"

  - name: deploy-zookeeper-on-warden-containerd
    plan:
      - in_parallel:
          - get: warden-cpi-containerd-image
            trigger: false
          - get: zookeeper-release
            trigger: false

      - task: start-bosh-and-deploy-zookeeper
        image: warden-cpi-containerd-image
        privileged: true
        config:
          platform: linux
          inputs:
            - name: zookeeper-release
          run:
            path: bash
            args:
              - -c
              - |
                set -euxo pipefail
                
                echo "=== Starting containerd daemon ==="
                mkdir -p /run/containerd
                containerd &
                
                # Wait for containerd to be ready
                for i in $(seq 1 30); do
                  if ctr version >/dev/null 2>&1; then
                    echo "containerd is ready"
                    break
                  fi
                  echo "Waiting for containerd... ($i/30)"
                  sleep 1
                done
                
                echo "=== Starting BOSH Director with Warden CPI (containerd backend) ==="
                start-bosh
                
                # Source the environment variables
                source /tmp/local-bosh/director/env
                
                echo "=== BOSH Director Environment ==="
                echo "BOSH_ENVIRONMENT: ${BOSH_ENVIRONMENT}"
                echo "BOSH_CLIENT: ${BOSH_CLIENT}"
                
                echo "=== Verifying BOSH Director ==="
                bosh env
                
                echo "=== Cloud Config ==="
                bosh cloud-config
                
                echo "=== Creating and Uploading Zookeeper Release ==="
                cd zookeeper-release
                bosh create-release --force --timestamp-version
                bosh upload-release
                cd ..
                
                echo "=== Uploading Stemcell ==="
                bosh upload-stemcell --sha1 8fbcaa623769ec29c39f4c8679337a8c95e8e4a8 \
                  https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-jammy-go_agent?v=1.632
                
                echo "=== Creating ops-file for single instance ==="
                cat > /tmp/single-instance.yml <<'OPSFILE'
                ---
                - type: replace
                  path: /instance_groups/name=zookeeper/instances
                  value: 1
                
                - type: replace
                  path: /instance_groups/name=zookeeper/azs
                  value: [z1]
                
                - type: remove
                  path: /instance_groups/name=smoke-tests
                
                - type: replace
                  path: /stemcells/alias=default/os
                  value: ubuntu-jammy
                OPSFILE
                
                echo "=== Deploying Zookeeper (Single Instance) ==="
                bosh -n deploy \
                  -d zookeeper \
                  zookeeper-release/manifests/zookeeper.yml \
                  -o /tmp/single-instance.yml
                
                echo "=== Deployment Status ==="
                bosh -d zookeeper instances
                
                echo "=== Zookeeper VMs ==="
                bosh -d zookeeper vms
                
                echo "=== Testing Zookeeper ==="
                bosh -d zookeeper ssh zookeeper/0 -c "
                  set -e
                  echo '=== Zookeeper Process Status ==='
                  sudo /var/vcap/bosh/bin/monit summary
                  
                  echo '=== Zookeeper Server Status ==='
                  echo stat | nc localhost 2181 || echo 'Could not connect to Zookeeper'
                "
                
                echo "=== Cleaning Up ==="
                bosh -d zookeeper -n delete-deployment
                
                echo "=== Pipeline Complete - Warden CPI with Containerd SUCCESS ==="
